import Footer from "@/components/footer/Footer";
import Header from "@/components/header/header";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Register Page",
    description: "Generated by create next app",
};

export default function ArchiveLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
        <Header />
            {children}
        <Footer />
        </>
    );
}
