import Footer from "@/components/footer/footerSection";
import Header from "@/components/header/header";
import type { Metadata } from "next";
import SidebarWrapper from "./sidebar";

export const metadata: Metadata = {
    title: "User Dashboard",
    description: "Generated by create next app",
};

export default function ArchiveLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <Header />
                <section>
                    <div className="container">

                            <div className="flex flex-col lg:flex-row">

                                {/* Sidebar */}
                                <SidebarWrapper />

                                {/* MAIN CONTENT */}
                                {children}
                            </div>
                    </div>
                </section>
            <Footer />
        </>
    );
}
